const fontFamilyName = {
  Montserrat: 'Montserrat',
  Poppins: 'Poppins',
};
const type = {
  Montserrat_Black: `${fontFamilyName.Montserrat}-Black`,
  Montserrat_BlackItalic: `${fontFamilyName.Montserrat}-BlackItalic`,
  Montserrat_Bold: `${fontFamilyName.Montserrat}-Bold`,
  Montserrat_BoldItalic: `${fontFamilyName.Montserrat}-BoldItalic`,
  Montserrat_ExtraBold: `${fontFamilyName.Montserrat}-ExtraBold`,
  Montserrat_ExtraBoldItalic: `${fontFamilyName.Montserrat}-ExtraBoldItalic`,
  Montserrat_ExtraLight: `${fontFamilyName.Montserrat}-ExtraLight`,
  Montserrat_ExtraLightItalic: `${fontFamilyName.Montserrat}-ExtraLightItalic`,
  Montserrat_Italic: `${fontFamilyName.Montserrat}-Italic`,
  Montserrat_Light: `${fontFamilyName.Montserrat}-Light`,
  Montserrat_LightItalic: `${fontFamilyName.Montserrat}-LightItalic`,
  Montserrat_Medium: `${fontFamilyName.Montserrat}-Medium`,
  Montserrat_MediumItalic: `${fontFamilyName.Montserrat}-MediumItalic`,
  Montserrat_Regular: `${fontFamilyName.Montserrat}-Regular`,
  Montserrat_SemiBold: `${fontFamilyName.Montserrat}-SemiBold`,
  Montserrat_SemiBoldItalic: `${fontFamilyName.Montserrat}-SemiBoldItalic`,
  Montserrat_Thin: `${fontFamilyName.Montserrat}-Thin`,
  Montserrat_ThinItalic: `${fontFamilyName.Montserrat}-ThinItalic`,
  Poppins_Black: `${fontFamilyName.Poppins}-Black`,
  Poppins_BlackItalic: `${fontFamilyName.Poppins}-BlackItalic`,
  Poppins_Bold: `${fontFamilyName.Poppins}-Bold`,
  Poppins_BoldItalic: `${fontFamilyName.Poppins}-BoldItalic`,
  Poppins_ExtraBold: `${fontFamilyName.Poppins}-ExtraBold`,
  Poppins_ExtraBoldItalic: `${fontFamilyName.Poppins}-ExtraBoldItalic`,
  Poppins_ExtraLight: `${fontFamilyName.Poppins}-ExtraLight`,
  Poppins_ExtraLightItalic: `${fontFamilyName.Poppins}-ExtraLightItalic`,
  Poppins_Italic: `${fontFamilyName.Poppins}-Italic`,
  Poppins_Light: `${fontFamilyName.Poppins}-Light`,
  Poppins_LightItalic: `${fontFamilyName.Poppins}-LightItalic`,
  Poppins_Medium: `${fontFamilyName.Poppins}-Medium`,
  Poppins_MediumItalic: `${fontFamilyName.Poppins}-MediumItalic`,
  Poppins_Regular: `${fontFamilyName.Poppins}-Regular`,
  Poppins_SemiBold: `${fontFamilyName.Poppins}-SemiBold`,
  Poppins_SemiBoldItalic: `${fontFamilyName.Poppins}-SemiBoldItalic`,
  Poppins_Thin: `${fontFamilyName.Poppins}-Thin`,
  Poppins_ThinItalic: `${fontFamilyName.Poppins}-ThinItalic`,
};

export default {
  type,
};
